name: Java CI with Gradle  
  
on:    
  pull_request:    
    branches: [ "main" ]  
  push:    
    branches: [ "main" ]  
  
jobs:  
  build:  
    if: github.event_name == 'pull_request'  
    runs-on: self-hosted    
    permissions:    
      contents: read    
  
    steps:    
    - uses: actions/checkout@v2 
    - name: Set up JDK 17  
      uses: actions/setup-java@v2   
      with:  
        java-version: '17'  
        distribution: 'temurin'  
    - name: Grant execute permission for gradlew    
      run: chmod +x ./be/gradlew  
  
    - name: Build with Gradle Wrapper    
      run: ./gradlew build    
      working-directory: ./be  
  
    - name: Archive build artifacts    
      uses: actions/upload-artifact@v3    
      with:    
        name: build-artifact  
        path: ./be/build/libs/*.jar  

  deploy:  
    if: github.event_name == 'push'  
    runs-on: self-hosted   
  
    steps:  
    - uses: actions/checkout@v2  
  
    - name: Log in to Docker Hub  
      uses: docker/login-action@v1  
      with:  
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}    
  
    - name: Build Docker image  
      run: docker build -t dyland0626/seedling:latest -f ./be/Dockerfile ./be  
  
    - name: Push Docker image  
      run: docker push dyland0626/seedling:latest  
